"""Every user-facing string the engine produces, in one place.

English only for now. A locale is added by giving this module a sibling with
the same names, not by editing call sites.
"""

from __future__ import annotations

# ---- optimizer ----
NUM_SLOTS_TOO_SMALL = "The number of slots must be at least 1."
BAD_SLOTS_PER_ENTITY = "Slots per entity must be a range with 0 <= min <= max (got {min}-{max})."
INTERCHANGEABLE_NEEDS_SINGLE_SLOT = "Slots can only be interchangeable when each entity holds exactly one slot."
RULE_NAMES_MISSING_SLOT = "Rule '{label}' names slot {slot}, which does not exist (slots are 1..{num_slots})."
SLOT_DOES_NOT_EXIST = "Slot {slot} does not exist (slots are 1..{num_slots})."
FIXED_TO_MISSING_SLOT = "Entity {entity} is fixed to slot {slot}, which does not exist (slots are 1..{num_slots})."
UNKNOWN_RULE_TYPE = "Unknown rule type: {type}"
NO_SOLUTION = "No assignment meets every mandatory rule, or the time limit ran out before one was found."

# ---- feasibility ----
FEAS_NO_SLOTS = "Number of slots"
FEAS_FEWER_ENTITIES_THAN_SLOTS_RULE = "Entities vs. slots"
FEAS_FEWER_ENTITIES_THAN_SLOTS = "There are only {n} entities for {k} slots, so some slots must stay empty."
FEAS_GROUP_TOTAL = "{total} in the group in total."
FEAS_GROUP_PLACES = "The group can fill between {fewest} and {most} places in these {count} slots."
FEAS_LOAD_OK = "Every member can hold this many slots."
FEAS_LOAD_MIN_UNREACHABLE = "Needs at least {lo} slots each, but some members can hold at most {most}."
FEAS_LOAD_MAX_UNREACHABLE = "Allows at most {hi} slots each, but some members must hold at least {fewest}."
FEAS_NEED_AT_LEAST = "At least {needed} needed ({lo} x {k} slots)."
FEAS_ROOM_FOR_AT_MOST = "Room for at most {capacity} ({hi} x {k} slots)."

# ---- verifier ----
INTEGRITY_LABEL = "Complete assignment"
INTEGRITY_OK = "Every entity holds an allowed number of slots, all of which exist."
INTEGRITY_MISSING = "{count} entities are not assigned"
INTEGRITY_WRONG_COUNT = "{count} entities hold a number of slots outside {min}-{max}"
INTEGRITY_UNKNOWN = "{count} assigned ids are not in the data"
INTEGRITY_OUT_OF_RANGE = "{count} entities hold a slot that does not exist, or the same slot twice"
CAPACITY_OK = "Every slot is within the range."
CAPACITY_BAD = "{count} slots are outside the range."
LOAD_OK = "Every entity in the group holds an allowed number of these slots."
LOAD_BAD = "{count} entities hold too many or too few of these slots."
RUN_OK = "Every stretch is within the allowed length."
RUN_BAD = "{count} entities have a stretch that is too long or too short."
TRANSITION_OK = "No forbidden sequence occurs."
TRANSITION_BAD = "{count} entities have a forbidden sequence."
PAIR_OK = "The rule holds for both entities."
PAIR_BAD = "The rule does not hold for these two entities."
PAIR_SAME = "share a slot"
PAIR_DIFFERENT = "never share a slot"
AT_LEAST_ONE_OK = "At least one entity from the list shares the slot."
AT_LEAST_ONE_BAD = "No entity from the list shares the slot."
AT_LEAST_ONE_EXPECTED = "at least 1"
FIXED_OK = "The fixed placement is kept."
FIXED_BAD = "The entity is not in the slot it is fixed to."
BALANCE_OK = "The group is spread evenly."
BALANCE_BAD = "The largest gap between slots is {gap}."
BALANCE_EXPECTED = "gap 0"
REQUESTS_NONE = "No requests were entered; this rule was not measured."
REQUESTS_OK = "Every request checked was met."
REQUESTS_BAD = "{count} entities have a request that was not met."
NO_CHECKER = "There is no independent check for rule type '{type}'."
VERIFY_VALID = "The assignment is valid: all {ok} mandatory checks passed."
VERIFY_INVALID = "The assignment is not valid: {bad} mandatory checks failed; {ok} passed."

# ---- options ----
STRATEGY_TITLES = {
    "balanced": "Current priorities",
    "preferences": "Favor requests",
    "balance": "Favor even slots",
}
REFINE_STEP_LABELS = ["Small change", "Medium change", "Free change"]
COMPROMISE_SINGLE = "Exception to: {label}"
COMPROMISE_MULTI = "Smallest exception"
TITLE_JOIN = " · "
SLOT_COUNT = "slot {slot}: {count}"
EXCEPTION_DETAIL = "{label} — {parts} (rule: {range})"
EXCEPTION_SUMMARY = "{label} — {summary}"
RANGE_UP_TO = "up to {hi}"
RANGE_AT_LEAST = "at least {lo}"
TRADEOFF_BEST = "{label}: {value} — best of the options"
TRADEOFF_WORST = "{label}: {value} — weakest of the options"
METRIC_SLOT_SIZE_SPREAD = "Gap between slot sizes"
METRIC_LOAD_SPREAD = "Gap between the most and fewest slots per entity"
METRIC_MOVED = "Entities moved from the base"
METRIC_RULE_SHORTFALL = "{label} (shortfall)"
QUESTION_ALL_VALID = "What matters more here: meeting more requests, or more even slots?"
QUESTION_ALL_VALID_REASON = "Every option meets every mandatory rule, and each favors a different goal."
QUESTION_COMPROMISE = "Which exception is easier to accept?"
QUESTION_COMPROMISE_REASON = (
    "No assignment meets every mandatory rule together; each option bends a different rule "
    "by the smallest amount found."
)

# ---- loading ----
FILE_NOT_FOUND = "File not found: {path}"
FILE_OPEN_ERROR = "Could not open {path}: {error}"
SHEET_NOT_FOUND = "Sheet '{sheet}' was not found. Available sheets: {sheets}"
SHEET_READ_ERROR = "Could not read sheet '{sheet}': {error}"
ID_COLUMN_NOT_UNIQUE = "The id column '{column}' must have a unique value in every row."
REMOVED_BLANK_ROWS = "Removed {count} completely blank rows."
REMOVED_ROWS_WITHOUT_ID = "Removed {count} rows with no value in '{column}'."
REMOVED_EMPTY_COLUMNS = "Removed empty columns: {columns}"

# ---- rule read-backs ----
# A read-back is assembled from these pieces by readback.py; nothing in it
# is free text written by the agent.
AND = "and"
OR = "or"
YES = "yes"
NO = "no"
BAND_EXACTLY = "exactly {n}"
BAND_BETWEEN = "between {lo} and {hi}"
BAND_AT_LEAST = "at least {n}"
BAND_AT_MOST = "at most {n}"
BAND_NONE = "no"
FILTER_FLAG = " marked {column}"
FILTER_VALUE = " whose {column} is {value}"
FILTER_MEMBERS = " among {members}"
SLOT_FILTER_WHERE = " where {conditions}"
SLOT_CONDITION = "{attribute} is {values}"
SLOT_FILTER_IDS = " among {ids}"
SUBJECT_EVERY_SLOT = "every {slot}{filter}"
SUBJECT_ONE_SLOT = "{slot} {id}"
SUBJECT_EACH_OF_SLOTS = "each of the {slots} {ids}"
SUBJECT_EACH_ENTITY = "each {entity}{filter}"
PER = " per {attribute}"
RB_CAPACITY = "{subject} has {band} {who}."
RB_LOAD = "{subject} has {band} {what}{per}."
RB_RUN_WORK = "{subject} works stretches of {band} {unit}{counting}{edge}."
RB_RUN_OFF = "{subject} has {units} off in stretches of {band} {unit}{counting}{edge}."
RUN_COUNTING = ", counting only {slots}{filter}"
RUN_EDGE = " (a stretch at the start or end of the schedule may be shorter)"
RB_TRANSITION = "After a {slot}{after}, {subject} has no {slot}{forbid} {window}."
WINDOW_NEXT = "the next {unit}"
WINDOW_NEXT_N = "in the next {n} {units}"
RB_BALANCE_GROUP = "Spread {who} evenly across the {slots}."
RB_BALANCE_BY_COLUMN = "Spread {entities} evenly across the {slots} by {column}."
RB_BALANCE_FLAGS = "Spread {entities} marked {columns} evenly across the {slots}, each separately."
RB_TOGETHER_ONE = "{a} and {b} are in the same {slot}."
RB_TOGETHER_MANY = "{a} and {b} share at least one {slot}."
RB_SEPARATE_ONE = "{a} and {b} are never in the same {slot}."
RB_SEPARATE_MANY = "{a} and {b} never share a {slot}."
RB_AT_LEAST_ONE_ONE = "{entity} is in the same {slot} as at least one of {candidates}."
RB_AT_LEAST_ONE_MANY = "{entity} shares a {slot} with at least one of {candidates}."
RB_FIXED_ONE = "{entity} is in {slot} {id}."
RB_FIXED_MANY = "{entity} has {slot} {id}."
RB_PARTNERS = (
    "Each {entity} who made requests is placed with a {entity} who asked for them back, and with at least "
    "two of the {entities} they asked for ({count} made requests)."
)
RB_SLOTS_PER_ENTITY = "Each {entity} has {band} {what}."
RB_HARD = "Mandatory."
RB_SOFT = "Preference, {level} priority."
RB_INACTIVE = "Switched off."
PRIORITY_NAMES = {"low": "low", "medium": "medium", "high": "high"}

# ---- spec checks ----
SPEC_SELECTOR_MEMBERS_OR_COLUMN = "An entity selector uses either 'members' or 'column' (with an optional 'value'), not both."
SPEC_VALUE_NEEDS_COLUMN = "'value' needs a 'column'."
SPEC_SLOTS_IDS_OR_WHERE = "A slot selector uses either 'ids' or 'where', not both."
SPEC_BAD_SLOTS_PER_ENTITY = "slots_per_entity must be [min, max] with 0 <= min <= max."
SPEC_PRIORITY_ON_HARD_RULE = "Only soft rules take a priority; a hard rule must always hold."
SPEC_BAND_EMPTY = "Give 'min', 'max' or both."
SPEC_BAND_REVERSED = "'min' cannot be larger than 'max'."
SPEC_BALANCE_ONE_TARGET = "A balance rule takes exactly one of 'entities', 'by_column' or 'flag_columns'."
SPEC_DUPLICATE_IDS = "Duplicate {kind} ids: {ids}."
SPEC_PROBLEM = "Rule {rule}: {message}"
SPEC_UNKNOWN_ID_COLUMN = "The id column '{column}' is not in the sheet. Columns: {columns}."
SPEC_UNKNOWN_ENTITY = "there is no entity '{entity}' in the data."
SPEC_UNKNOWN_COLUMN = "there is no column '{column}'. Columns: {columns}."
SPEC_NOT_A_FLAG = "column '{column}' is not a yes/no column (it holds {values}); give a 'value' to pick rows."
SPEC_UNKNOWN_VALUE = "no row has {column} = {value}. Values in the data: {values}."
SPEC_UNKNOWN_SLOT = "there is no slot '{slot}'."
SPEC_UNKNOWN_ATTRIBUTE = "no slot has the attribute '{attribute}'. Slot attributes: {attributes}."
SPEC_NO_SLOTS_SELECTED = "the slot selection matches no slot."
SPEC_SLOT_MISSING_ATTRIBUTE = "slot '{slot}' has no '{attribute}' attribute."
SPEC_SAME_ENTITY_TWICE = "'{entity}' is named twice; the rule needs two different entities."
SPEC_DUPLICATE_ENTITIES = "The entity table has duplicate ids."
SPEC_TOO_MANY_SLOTS_PER_ENTITY = "slots_per_entity allows {max} slots each, but there are only {count} slots."
